"""
WebEase — Document Service
Handles .docx file generation and text extraction using python-docx.
"""

import logging
import os
from datetime import datetime
from docx import Document
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

import config

logger = logging.getLogger("webease.document")


class DocumentService:

    def generate_docx(self, title: str, content: str, filename: str) -> dict:
        """
        Create a .docx file with the given title and content.
        Returns: { "filepath": str, "filename": str, "status": str }
        """
        try:
            doc = Document()

            # Title styling
            title_para = doc.add_heading(title, level=1)
            title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
            run = title_para.runs[0]
            run.font.color.rgb = RGBColor(0x1d, 0x4e, 0xd8)

            # Metadata line
            meta = doc.add_paragraph()
            meta.add_run(f"Generated by WebEase AI  •  {datetime.now().strftime('%B %d, %Y')}")
            meta.runs[0].font.size = Pt(9)
            meta.runs[0].font.color.rgb = RGBColor(0x64, 0x74, 0x8b)

            doc.add_paragraph()  # spacer

            # Body content — split on newlines for proper paragraphs
            for para_text in content.split("\n"):
                if para_text.strip():
                    para = doc.add_paragraph(para_text.strip())
                    para.runs[0].font.size = Pt(11)

            # Save
            safe_name = "".join(c if c.isalnum() or c in "-_" else "_" for c in filename)
            out_path = os.path.join(config.DOCS_OUTPUT_DIR, f"{safe_name}.docx")
            doc.save(out_path)

            logger.info(f"Document saved: {out_path}")
            return {"filepath": out_path, "filename": f"{safe_name}.docx", "status": "success"}

        except Exception as e:
            logger.error(f"Document generation error: {e}")
            return {"filepath": None, "filename": None, "status": "error", "detail": str(e)}

    def extract_text(self, filepath: str) -> dict:
        """
        Extract plain text from a .docx file.
        Returns: { "text": str, "status": str }
        """
        try:
            doc = Document(filepath)
            paragraphs = [p.text for p in doc.paragraphs if p.text.strip()]
            return {"text": "\n".join(paragraphs), "status": "success"}
        except Exception as e:
            logger.error(f"Document read error: {e}")
            return {"text": "", "status": "error", "detail": str(e)}


# Singleton instance
document_service = DocumentService()
